package ETC;

public class Ex02_Exception {
	public static void main(String[] args) {
		int num = 100;
		int result = 0;
		System.out.println("main start");
		
		for(int i = 0; i < 10; i++) {
			result = num/(int)(Math.random()*10); // 0 ~ 9
			System.out.println("결과 result : " + result + " i ");
			
		}	
	} catch(ArithemeticException e) {
		
		System.out.println("문제가 발생 관리자에게 메일 발송");
		System.out.println("원인 : " + e.getMessage());
	}
}
